### ISSUE TITLE
Crosshair Problem

### ISSUE THREAD

**Issue by RunawaySheld123** [Hypnootize/yayahud#1]
I Have A Problem With Crosshair

**Comment by Hypnootize** [comment]
I'm afraid i need a bit more infos than that...
whats not working? which crosshair, all of them or just one?

**Comment by RunawaySheld123** [comment]
All Of Them When I Enable The Crosshair The Crosshair Is Missing In The Game

**Comment by Hypnootize** [comment]
Should work now!
